# -*- coding: utf-8 -*-
"""Temprature.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rozJG8bDUlyhZSJIsSrekoQnH_3ABq5H
"""

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import math 
from tensorflow import keras

tf.__version__

df = pd.read_csv("EcoTrans-AQIFinalDataSet - Temprature Cleaned.csv")

df.head()

plt.figure(figsize = (14,7))
plt.plot(range(len(df["JakartaTempratureCelcius"])),df["JakartaTempratureCelcius"])

dfcelcius = df["JakartaTempratureCelcius"]


dfcelcius

def split_counter(df,split_size):
  training = math.floor(len(df)*split_size)
  testing = math.floor(len(df) - training)

  training_set = df[:training]
  testing_set = df[training:]
  print("We have  {} for training and we have {} for testing".format(training,testing))


  return  training_set,testing_set

training_set, testing_set = split_counter(dfcelcius,0.8)

testing_set

a = np.array(training_set)

shuffle_buffer_size = 1000
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    series = tf.expand_dims(series, axis=-1)
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size + 1))
    ds = ds.shuffle(shuffle_buffer)
    ds = ds.map(lambda w: (w[:-1], w[1:]))
    return ds.batch(batch_size).prefetch(1)


def model_forecast(model, series, window_size):
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size))
    ds = ds.batch(32).prefetch(1)
    forecast = model.predict(ds)
    return forecast

tf.keras.backend.clear_session()
tf.random.set_seed(51)
np.random.seed(51)
window_size = 64
batch_size = 256
train_set = windowed_dataset(a, window_size, batch_size, shuffle_buffer_size)
print(train_set)
print(a.shape)

model = tf.keras.models.Sequential([
  tf.keras.layers.Conv1D(filters=32, kernel_size=5,
                      strides=1, padding="causal",
                      activation="relu",
                      input_shape=[None, 1]),
  tf.keras.layers.LSTM(64, return_sequences=True),
  tf.keras.layers.LSTM(64, return_sequences=True),
  tf.keras.layers.Dense(30, activation="relu"),
  tf.keras.layers.Dense(10, activation="relu"),
  tf.keras.layers.Dense(1),
  tf.keras.layers.Lambda(lambda x: x * 400)
])

lr_schedule = tf.keras.callbacks.LearningRateScheduler(
    lambda epoch: 1e-8 * 10**(epoch / 20))
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-8, momentum=0.9)
model.compile(loss=tf.keras.losses.Huber(),
              optimizer=optimizer,
              metrics=["mae"])
history = model.fit(train_set, epochs=100, callbacks=[lr_schedule])

plt.semilogx(history.history["lr"], history.history["loss"])
plt.axis([1e-8, 1e-4, 0, 60])

tf.keras.backend.clear_session()
tf.random.set_seed(51)
np.random.seed(51)
train_set = windowed_dataset(a, window_size=60, batch_size=100, shuffle_buffer=shuffle_buffer_size)
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv1D(filters=60, kernel_size=5,
                      strides=1, padding="causal",
                      activation="relu",
                      input_shape=[None, 1]),
  tf.keras.layers.LSTM(64, return_sequences=True),
  tf.keras.layers.LSTM(64, return_sequences=True),
  tf.keras.layers.Dense(30, activation="relu"),
  tf.keras.layers.Dense(10, activation="relu"),
  tf.keras.layers.Dense(1),
  tf.keras.layers.Lambda(lambda x: x * 400)
])


optimizer = tf.keras.optimizers.SGD(learning_rate=5e-6, momentum=0.9)
model.compile(loss=tf.keras.losses.Huber(),
              optimizer=optimizer,
              metrics=["mae"])
history = model.fit(train_set,epochs=600)

model.summary()

datas= np.array(dfcelcius)
datas

def model_forecast(model, series, window_size):
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size))
    ds = ds.batch(32).prefetch(1)
    forecast = model.predict(ds)
    return forecast

rnn_forecast = model_forecast(model, datas[..., np.newaxis], window_size)
rnn_forecast = rnn_forecast[(7008 - window_size):-1, -1, 0]
rnn_forecast

cobacoba2 = np.random.randint(25,35,70)
len(cobacoba2)

rnn_forecast2 = model_forecast(model, cobacoba2[..., np.newaxis], window_size)
rnn_forecast2 = rnn_forecast2[(64 - window_size):-1, -1, 0]
print(rnn_forecast2)

def cvrttolist (listy) : 
  return listy.tolist()
def extenddf(df,forecast):
  a= cvrttolist(df)
  b=cvrttolist(forecast)
  a.extend(b)
  return np.array(a) 
  
def model_forecast(model, series, window_size):
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size))
    ds = ds.batch(32).prefetch(1)
    forecast = model.predict(ds)
    return forecast

    
def forecasttemprature (df, hour):
  for nexttemprature in range(hour) :
    lstm_forecast2 = model_forecast(Temprature, df[..., np.newaxis], window_size)
    lstm_forecast2 = lstm_forecast2[((len(df)-1) - window_size):-1, -1, 0]
    df=extenddf(df,lstm_forecast2)
  
    lstm_forecast2 = model_forecast(Temprature, df[..., np.newaxis], window_size)
    lstm_forecast2 = lstm_forecast2[((len(df)-1) - window_size):-1, -1, 0]
    df=extenddf(df,lstm_forecast2)

    df=cvrttolist(df)
    a=df[-2]
    df.remove(a)
    df=np.array(df)

  return lstm_forecast2

def plot_series(time, series, format="-", start=0, end=None):
    plt.plot(time[start:end], series[start:end], format)
    plt.xlabel("Time")
    plt.ylabel("Value")
    plt.grid(True)

plt.figure(figsize=(10, 6))
plot_series(range(len(testing_set)), testing_set)
plot_series(range(len(testing_set)), rnn_forecast)

tf.keras.metrics.mean_absolute_error(testing_set, rnn_forecast).numpy()

#Making dataframe
frames = { "index":list(range(7008,8760)), "Temprature":testing_set, "Temprature-Forcast": rnn_forecast}
dfforcast = pd.DataFrame(frames)
dfforcast["Hour"] = dfforcast["index"]%24
dfforcast

from google.colab import drive
drive.mount('/gdrive')

model.save('saved_model/Temprature')

Temprature = tf.keras.models.load_model('/gdrive/MyDrive/saved_model/Temprature')

# Check its architecture
Temprature.summary()



